animals_dict = {
    "Lion": "Animals",
    "Tiger": "Animals",
    "Elephant": "Animals",
    "Giraffe": "Animals",
    "Zebra": "Animals",
    "Bear": "Animals",
    "Panda": "Animals",
    "Kangaroo": "Animals",
    "Koala": "Animals",
    "Penguin": "Animals",
    "Gorilla": "Animals",
    "Monkey": "Animals",
    "Hippopotamus": "Animals",
    "Rhinoceros": "Animals",
    "Cheetah": "Animals",
    "Leopard": "Animals",
    "Jaguar": "Animals",
    "Hyena": "Animals",
    "Wolf": "Animals",
    "Fox": "Animals",
    "Deer": "Animals",
    "Moose": "Animals",
    "Elk": "Animals",
    "Bison": "Animals",
    "Buffalo": "Animals",
    "Horse": "Animals",
    "Donkey": "Animals",
    "Camel": "Animals",
    "Llama": "Animals",
    "Alpaca": "Animals",
    "Sheep": "Animals",
    "Goat": "Animals",
    "Pig": "Animals",
    "Cow": "Animals",
    "Chicken": "Animals",
    "Duck": "Animals",
    "Turkey": "Animals",
    "Goose": "Animals",
    "Ostrich": "Animals",
    "Emu": "Animals",
    "Peacock": "Animals",
    "Flamingo": "Animals",
    "Pelican": "Animals",
    "Seagull": "Animals",
    "Hawk": "Animals",
    "Eagle": "Animals",
    "Owl": "Animals",
    "Falcon": "Animals",
    "Vulture": "Animals",
    "Parrot": "Animals",
    "Canary": "Animals",
    "Sparrow": "Animals",
    "Swallow": "Animals",
    "Hummingbird": "Animals",
    "Bat": "Animals",
    "Rat": "Animals",
    "Mouse": "Animals",
    "Squirrel": "Animals",
    "Hedgehog": "Animals",
    "Rabbit": "Animals",
    "Guinea Pig": "Animals",
    "Ferret": "Animals",
    "Weasel": "Animals",
    "Otter": "Animals",
    "Beaver": "Animals",
    "Raccoon": "Animals",
    "Skunk": "Animals",
    "Badger": "Animals",
    "Wolverine": "Animals",
    "Lynx": "Animals",
    "Cougar": "Animals",
    "Puma": "Animals",
    "Cheetah": "Animals",
    "Serval": "Animals",
    "Caracal": "Animals",
    "Bobcat": "Animals",
    "Snow Leopard": "Animals",
    "Clouded Leopard": "Animals",
    "Asian Elephant": "Animals",
    "African Elephant": "Animals",
    "Indian Elephant": "Animals",
    "Gaur": "Animals",
    "Bongo": "Animals",
    "Okapi": "Animals",
    "Antelope": "Animals",
    "Gazelle": "Animals",
    "Impala": "Animals",
    "Kudu": "Animals",
    "Springbok": "Animals",
    "Wildebeest": "Animals",
    "Sable Antelope": "Animals",
    "Eland": "Animals",
    "Oryx": "Animals",
    "Saiga Antelope": "Animals",
    "Muskox": "Animals",
    "Narwhal": "Animals",
    "Beluga Whale": "Animals",
    "Humpback Whale": "Animals",
    "Blue Whale": "Animals",
    "Killer Whale": "Animals",
    "Dolphin": "Animals",
    "Porpoise": "Animals",
    "Seal": "Animals",
    "Sea Lion": "Animals",
    "Walrus": "Animals",
    "Manatee": "Animals",
    "Sea Otter": "Animals",
    "Jellyfish": "Animals",
    "Octopus": "Animals",
    "Squid": "Animals",
    "Starfish": "Animals",
    "Sea Urchin": "Animals",
    "Coral": "Animals",
    "Sea Anemone": "Animals",
    "Lobster": "Animals",
    "Crab": "Animals",
    "Shrimp": "Animals",
    "Clam": "Animals",
    "Mussel": "Animals",
    "Oyster": "Animals",
    "Scallop": "Animals",
    "Abalone": "Animals",
    "Barnacle": "Animals",
    "Cockroach": "Animals",
    "Ant": "Animals",
    "Bee": "Animals",
    "Wasp": "Animals",
    "Butterfly": "Animals",
    "Moth": "Animals",
    "Dragonfly": "Animals",
    "Ladybug": "Animals",
    "Spider": "Animals",
    "Tick": "Animals",
    "Scorpion": "Animals",
    "Centipede": "Animals",
    "Millipede": "Animals",
    "Earthworm": "Animals",
    "Leech": "Animals",
    "Slug": "Animals",
    "Snail": "Animals",
    "Newt": "Animals",
    "Salamander": "Animals",
    "Frog": "Animals",
    "Toad": "Animals",
    "Iguana": "Animals",
    "Gecko": "Animals",
    "Chameleon": "Animals",
    "Komodo Dragon": "Animals",
    "Monitor Lizard": "Animals",
    "Anole": "Animals",
    "Skink": "Animals",
    "Turtle": "Animals",
    "Tortoise": "Animals",
    "Crocodile": "Animals",
    "Alligator": "Animals",
    "Gharial": "Animals",
    "Basilisk": "Animals",
    "Gila Monster": "Animals",
    "Horned Lizard": "Animals",
    "Rattlesnake": "Animals",
    "Viper": "Animals",
    "Copperhead": "Animals",
    "Boa Constrictor": "Animals",
    "Python": "Animals",
    "Anaconda": "Animals",
    "Coral Snake": "Animals",
    "King Cobra": "Animals",
    "Mamba": "Animals",
    "Eel": "Animals",
    "Lamprey": "Animals",
    "Hagfish": "Animals",
    "Sturgeon": "Animals",
    "Pufferfish": "Animals",
    "Clownfish": "Animals",
    "Angelfish": "Animals",
    "Seahorse": "Animals",
    "Mandarinfish": "Animals",
    "Grouper": "Animals",
    "Snapper": "Animals",
    "Tuna": "Animals",
    "Swordfish": "Animals",
    "Marlin": "Animals",
    "Mackerel": "Animals",
    "Salmon": "Animals",
    "Trout": "Animals",
    "Bass": "Animals",
    "Catfish": "Animals",
    "Tilapia": "Animals",
    "Barracuda": "Animals",
    "Jellyfish": "Animals",
    "Sea Cucumber": "Animals"
}