cities_dict = {
    "New York": "Cities",
    "Los Angeles": "Cities",
    "Chicago": "Cities",
    "Houston": "Cities",
    "Phoenix": "Cities",
    "Philadelphia": "Cities",
    "San Antonio": "Cities",
    "San Diego": "Cities",
    "Dallas": "Cities",
    "San Jose": "Cities",
    "Austin": "Cities",
    "Jacksonville": "Cities",
    "San Francisco": "Cities",
    "Indianapolis": "Cities",
    "Columbus": "Cities",
    "Fort Worth": "Cities",
    "Charlotte": "Cities",
    "San Francisco": "Cities",
    "Seattle": "Cities",
    "Denver": "Cities",
    "Washington": "Cities",
    "Boston": "Cities",
    "El Paso": "Cities",
    "Nashville": "Cities",
    "Detroit": "Cities",
    "Oklahoma City": "Cities",
    "Las Vegas": "Cities",
    "Memphis": "Cities",
    "Baltimore": "Cities",
    "Milwaukee": "Cities",
    "Albuquerque": "Cities",
    "Tucson": "Cities",
    "Fresno": "Cities",
    "Sacramento": "Cities",
    "Kansas City": "Cities",
    "Mesa": "Cities",
    "Atlanta": "Cities",
    "Colorado Springs": "Cities",
    "Virginia Beach": "Cities",
    "Raleigh": "Cities",
    "Omaha": "Cities",
    "Miami": "Cities",
    "Cleveland": "Cities",
    "Tulsa": "Cities",
    "Oakland": "Cities",
    "Minneapolis": "Cities",
    "Wichita": "Cities",
    "Arlington": "Cities",
    "Bakersfield": "Cities",
    "Tampa": "Cities",
    "Aurora": "Cities",
    "Honolulu": "Cities",
    "Anaheim": "Cities",
    "Santa Ana": "Cities",
    "St Louis": "Cities",
    "Riverside": "Cities",
    "Corpus Christi": "Cities",
    "Lexington": "Cities",
    "Stockton": "Cities",
    "Henderson": "Cities",
    "Saint Paul": "Cities",
    "Cincinnati": "Cities",
    "Anchorage": "Cities",
    "Greensboro": "Cities",
    "Plano": "Cities",
    "Newark": "Cities",
    "Durham": "Cities",
    "Chula Vista": "Cities",
    "Toledo": "Cities",
    "Madison": "Cities",
    "Laredo": "Cities",
    "Lubbock": "Cities",
    "Reno": "Cities",
    "Buffalo": "Cities",
    "Chandler": "Cities",
    "Scottsdale": "Cities",
    "Glendale": "Cities",
    "Jersey City": "Cities",
    "Richmond": "Cities",
    "Irving": "Cities",
    "Hialeah": "Cities",
    "Garland": "Cities",
    "Fremont": "Cities",
    "Baton Rouge": "Cities",
    "Des Moines": "Cities",
    "Modesto": "Cities",
    "Fargo": "Cities",
    "Tacoma": "Cities",
    "Columbia": "Cities",
    "Downey": "Cities",
    "Costa Mesa": "Cities",
    "Wilmington": "Cities",
    "Saint Petersburg": "Cities",
    "West Valley City": "Cities",
    "Norfolk": "Cities",
    "Olathe": "Cities",
    "Newport News": "Cities",
    "Cape Coral": "Cities",
    "Corona": "Cities",
    "Orange": "Cities",
    "Fullerton": "Cities",
    "Killeen": "Cities",
    "Akron": "Cities",
    "Little Rock": "Cities",
    "Augusta": "Cities",
    "Evansville": "Cities",
    "Cedar Rapids": "Cities",
    "Gainesville": "Cities",
    "Mobile": "Cities",
    "Columbus": "Cities",
    "Huntsville": "Cities",
    "Augusta": "Cities",
    "Grand Prairie": "Cities",
    "Grand Rapids": "Cities",
    "Salt Lake City": "Cities",
    "Frisco": "Cities",
    "Yonkers": "Cities",
    "Overland Park": "Cities",
    "Tempe": "Cities",
    "McKinney": "Cities",
    "Surprise": "Cities",
    "Rochester": "Cities",
    "Orem": "Cities",
    "Sandy Springs": "Cities",
    "Macon": "Cities",
    "Dothan": "Cities",
    "Gainesville": "Cities",
    "Cary": "Cities",
    "Boulder": "Cities",
    "Cleveland": "Cities",
    "St Louis Park": "Cities",
    "Peoria": "Cities",
    "Syracuse": "Cities",
    "Providence": "Cities",
    "Duluth": "Cities",
    "Morgantown": "Cities",
    "Charleston": "Cities",
    "Florence": "Cities",
    "Lancaster": "Cities",
    "West Palm Beach": "Cities",
    "Haverhill": "Cities",
    "New Haven": "Cities",
    "Albany": "Cities",
    "Binghamton": "Cities",
    "Syracuse": "Cities",
    "Jackson": "Cities",
    "Lansing": "Cities",
    "Gulfport": "Cities",
    "Biloxi": "Cities",
    "Longview": "Cities",
    "Texarkana": "Cities",
    "Beaumont": "Cities",
    "Lufkin": "Cities",
    "Kerrville": "Cities",
    "Huntsville": "Cities",
    "Madison": "Cities",
    "Montgomery": "Cities",
    "Augusta": "Cities",
    "Athens": "Cities",
    "Savannah": "Cities",
    "Jacksonville": "Cities",
    "Daytona Beach": "Cities",
    "Port St. Lucie": "Cities",
    "Palm Bay": "Cities",
    "Melbourne": "Cities",
    "Tallahassee": "Cities",
    "Pensacola": "Cities",
    "Tampa Bay": "Cities",
    "Orlando": "Cities",
    "Winter Haven": "Cities",
    "Ocala": "Cities",
    "Deltona": "Cities",
    "Palm Coast": "Cities",
    "Gainesville": "Cities",
    "Sarasota": "Cities",
    "Naples": "Cities",
    "Fort Myers": "Cities",
    "Cape Coral": "Cities",
    "Bradenton": "Cities",
    "Port Charlotte": "Cities",
    "Lehigh Acres": "Cities",
    "Sanford": "Cities",
    "Winter Park": "Cities",
    "Altamonte Springs": "Cities",
    "Apopka": "Cities",
    "Titusville": "Cities",
    "Cocoa": "Cities",
    "Vero Beach": "Cities",
    "Sebastian": "Cities",
    "Fort Pierce": "Cities",
    "Stuart": "Cities",
    "Okeechobee": "Cities"
}