movies_dict = {
    "The Matrix": "Movies",
    "Inception": "Movies",
    "Pulp Fiction": "Movies",
    "The Shawshank Redemption": "Movies",
    "Interstellar": "Movies",
    "The Godfather": "Movies",
    "Fight Club": "Movies",
    "The Dark Knight": "Movies",
    "Forrest Gump": "Movies",
    "The Lord of the Rings": "Movies",
    "Gladiator": "Movies",
    "The Departed": "Movies",
    "Inglourious Basterds": "Movies",
    "The Social Network": "Movies",
    "Seven": "Movies",
    "Parasite": "Movies",
    "The Lion King": "Movies",
    "Back to the Future": "Movies",
    "Jurassic Park": "Movies",
    "The Silence of the Lambs": "Movies",
    "Avatar": "Movies",
    "The Usual Suspects": "Movies",
    "Goodfellas": "Movies",
    "The Big Lebowski": "Movies",
    "Casablanca": "Movies",
    "The Grand Budapest Hotel": "Movies",
    "Mad Max Fury Road": "Movies",
    "The Revenant": "Movies",
    "Whiplash": "Movies",
    "Her": "Movies",
    "Blade Runner 2049": "Movies",
    "The Prestige": "Movies",
    "Django Unchained": "Movies",
    "Skyfall": "Movies",
    "Memento": "Movies",
    "The Intouchables": "Movies",
    "The Hunt": "Movies",
    "The Shining": "Movies",
    "A Beautiful Mind": "Movies",
    "12 Angry Men": "Movies",
    "The Wolf of Wall Street": "Movies",
    "The Green Mile": "Movies",
    "The Sixth Sense": "Movies",
    "The Big Short": "Movies",
    "Joker": "Movies",
    "La La Land": "Movies",
    "The Truman Show": "Movies",
    "No Country for Old Men": "Movies",
    "Inside Out": "Movies",
    "The Shape of Water": "Movies",
    "Sicario": "Movies",
    "Arrival": "Movies",
    "The Conjuring": "Movies",
    "Deadpool": "Movies",
    "Fargo": "Movies",
    "The Breakfast Club": "Movies",
    "The Imitation Game": "Movies",
    "Annihilation": "Movies",
    "The Lobster": "Movies",
    "Birdman": "Movies",
    "Snowpiercer": "Movies",
    "A Quiet Place": "Movies",
    "Midnight in Paris": "Movies",
    "The Great Gatsby": "Movies",
    "Jaws": "Movies",
    "Guardians of the Galaxy": "Movies",
    "The Martian": "Movies",
    "Doctor Strange": "Movies",
    "The Jungle Book": "Movies",
    "The Lego Movie": "Movies",
    "Zootopia": "Movies",
    "Shutter Island": "Movies",
    "Catch Me If You Can": "Movies",
    "Hereditary": "Movies",
    "It Follows": "Movies",
    "Get Out": "Movies",
    "Trollhunter": "Movies",
    "The Babadook": "Movies",
    "Oldboy": "Movies",
    "The Orphanage": "Movies",
    "Pans Labyrinth": "Movies",
    "Spirited Away": "Movies",
    "My Neighbor Totoro": "Movies",
    "Your Name": "Movies",
    "Kikis Delivery Service": "Movies",
    "The Pianist": "Movies",
    "The Thing": "Movies",
    "The Hunt for Red October": "Movies",
    "A Clockwork Orange": "Movies",
    "Moulin Rouge": "Movies",
    "The Exorcist": "Movies",
    "The Truman Show": "Movies",
    "The Witch": "Movies",
    "The Secret Life of Walter Mitty": "Movies",
    "Lady Bird": "Movies",
    "The Big Sick": "Movies",
    "Moonlight": "Movies",
    "The Florida Project": "Movies",
    "The Favourite": "Movies",
    "Roma": "Movies",
    "Hereditary": "Movies",
    "Jumanji Welcome to the Jungle": "Movies",
    "The Edge of Tomorrow": "Movies",
    "John Wick": "Movies",
    "Kingsman: The Secret Service": "Movies",
    "The Maze Runner": "Movies",
    "The Lego Batman Movie": "Movies",
    "The Nice Guys": "Movies",
    "Sicario: Day of the Soldado": "Movies",
    "Oceans Eleven": "Movies",
    "Trainspotting": "Movies",
    "Lock Stock and Two Smoking Barrels": "Movies",
    "Snatch": "Movies",
    "The Royal Tenenbaums": "Movies",
    "The Darjeeling Limited": "Movies",
    "Fantastic Mr Fox": "Movies",
    "The Life Aquatic with Steve Zissou": "Movies",
    "Moonrise Kingdom": "Movies",
    "Rushmore": "Movies",
    "The Master": "Movies",
    "The Grandmaster": "Movies",
    "The Hidden Fortress": "Movies",
    "Ikiru": "Movies",
    "The Seventh Seal": "Movies",
    "The Last Emperor": "Movies",
    "Ran": "Movies",
    "The Bridge on the River Kwai": "Movies",
    "Lawrence of Arabia": "Movies",
    "Ben-Hur": "Movies",
    "Gone with the Wind": "Movies",
    "Casablanca": "Movies",
    "Chinatown": "Movies",
    "The Godfather Part II": "Movies",
    "The French Connection": "Movies",
    "Network": "Movies",
    "Taxi Driver": "Movies",
    "The Deer Hunter": "Movies",
    "One Flew Over the Cuckoo's Nest": "Movies",
    "Vertigo": "Movies",
    "Rear Window": "Movies",
    "Psycho": "Movies",
    "North by Northwest": "Movies",
    "Sunset Boulevard": "Movies",
    "Some Like It Hot": "Movies",
    "The Apartment": "Movies",
    "To Kill a Mockingbird": "Movies",
    "On the Waterfront": "Movies",
    "A Streetcar Named Desire": "Movies",
    "The Philadelphia Story": "Movies",
    "Bringing Up Baby": "Movies",
    "The Thin Man": "Movies",
    "It Happened One Night": "Movies",
    "The Big Sleep": "Movies",
    "Double Indemnity": "Movies",
    "Laura": "Movies",
    "The Maltese Falcon": "Movies",
    "Gilda": "Movies",
    "Touch of Evil": "Movies",
    "The Lady from Shanghai": "Movies",
    "The Third Man": "Movies",
    "The Big Heat": "Movies",
    "Notorious": "Movies",
    "Strangers on a Train": "Movies",
    "Charade": "Movies",
    "The Manchurian Candidate": "Movies",
    "The Seventh Seal": "Movies"
}