# Riddles and answers
riddles = [
    {"riddle": "What can travel around the world while staying in a corner?", "answer": "stamp"},
    {"riddle": "What has a heart that doesn’t beat?", "answer": "artichoke"},
    {"riddle": "What gets wetter as it dries?", "answer": "towel"},
    {"riddle": "What has hands but can’t clap?", "answer": "clock"},
    {"riddle": "What has a neck but no head?", "answer": "bottle"},
    {"riddle": "What has one eye but can’t see?", "answer": "needle"},
    {"riddle": "What can you catch but not throw?", "answer": "cold"},
    {"riddle": "What goes up but never comes down?", "answer": "age"},
    {"riddle": "What can be cracked, made, told, and played?", "answer": "joke"},
    {"riddle": "What has many keys but can't open a single door?", "answer": "piano"},
    {"riddle": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "m"},
    {"riddle": "What has a thumb and four fingers but is not alive?", "answer": "glove"},
    {"riddle": "What has a head, a tail, is brown, and has no legs?", "answer": "penny"},
    {"riddle": "What has cities, but no houses; forests, but no trees; and rivers, but no water?", "answer": "map"},
    {"riddle": "What begins with T, ends with T, and has T in it?", "answer": "teapot"},
    {"riddle": "What is so fragile that saying its name breaks it?", "answer": "silence"},
    {"riddle": "What can be heard but not seen and only speaks when spoken to?", "answer": "echo"},
    {"riddle": "What can fill a room but takes up no space?", "answer": "light"},
    {"riddle": "What is full of holes but still holds water?", "answer": "sponge"},
    {"riddle": "The more you take, the more you leave behind. What am I?", "answer": "footsteps"},
    {"riddle": "What has many teeth but can’t bite?", "answer": "comb"},
    {"riddle": "What has one letter and starts and ends with an E but has only one letter?", "answer": "envelope"},
    {"riddle": "What is always coming but never arrives?", "answer": "tomorrow"},
    {"riddle": "What is black when it’s clean and white when it’s dirty?", "answer": "chalkboard"},
    {"riddle": "What can be broken but is never held?", "answer": "promise"},
    {"riddle": "What gets sharper the more you use it?", "answer": "brain"},
    {"riddle": "What has a bed but doesn’t sleep, and a mouth but doesn’t eat?", "answer": "river"},
    {"riddle": "What is as light as a feather, yet the strongest man can’t hold it for more than a few minutes?", "answer": "breath"},
    {"riddle": "What is always in front of you but can’t be seen?", "answer": "future"},
    {"riddle": "What starts with a P, ends with an E, and has thousands of letters?", "answer": "post office"},
    ]