songs_dict = {
    "Bohemian Rhapsody": "Songs",
    "Hotel California": "Songs",
    "Imagine": "Songs",
    "Hey Jude": "Songs",
    "Smells Like Teen Spirit": "Songs",
    "Like a Rolling Stone": "Songs",
    "Whats Going On": "Songs",
    "Billie Jean": "Songs",
    "I Want to Hold Your Hand": "Songs",
    "Purple Haze": "Songs",
    "Let It Be": "Songs",
    "Stairway to Heaven": "Songs",
    "Sweet Child O Mine": "Songs",
    "Livin on a Prayer": "Songs",
    "Superstition": "Songs",
    "Back in Black": "Songs",
    "Respect": "Songs",
    "With or Without You": "Songs",
    "Sweet Home Alabama": "Songs",
    "Dont Stop Believin'": "Songs",
    "Born to Run": "Songs",
    "I Will Always Love You": "Songs",
    "One": "Songs",
    "Africa": "Songs",
    "Under Pressure": "Songs",
    "Bohemian Like You": "Songs",
    "Wonderwall": "Songs",
    "Another Brick in the Wall": "Songs",
    "My Heart Will Go On": "Songs",
    "Every Breath You Take": "Songs",
    "Take On Me": "Songs",
    "Eye of the Tiger": "Songs",
    "Uptown Funk": "Songs",
    "Rolling in the Deep": "Songs",
    "Poker Face": "Songs",
    "Umbrella": "Songs",
    "Viva La Vida": "Songs",
    "Halo": "Songs",
    "Shake It Off": "Songs",
    "Royals": "Songs",
    "Somebody That I Used to Know": "Songs",
    "Happy": "Songs",
    "All About That Bass": "Songs",
    "Blinding Lights": "Songs",
    "Shape of You": "Songs",
    "Sunflower": "Songs",
    "Bad Guy": "Songs",
    "Old Town Road": "Songs",
    "Rockstar": "Songs",
    "Sicko Mode": "Songs",
    "Senorita": "Songs",
    "Watermelon Sugar": "Songs",
    "Montero Call Me By Your Name": "Songs",
    "Levitating": "Songs",
    "Peaches": "Songs",
    "Save Your Tears": "Songs",
    "Kiss Me More": "Songs",
    "Drivers License": "Songs",
    "Industry Baby": "Songs",
    "Stay": "Songs",
    "Leave The Door Open": "Songs",
    "Adore You": "Songs",
    "Therefore I Am": "Songs",
    "Positions": "Songs",
    "Dont Start Now": "Songs",
    "Everything I Wanted": "Songs",
    "Mood": "Songs",
    "Roses": "Songs",
    "Life Goes On": "Songs",
    "Stuck with U": "Songs",
    "Break My Heart": "Songs",
    "No Time to Die": "Songs",
    "Good Days": "Songs",
    "Dynamite": "Songs",
    "Bad Habits": "Songs",
    "Shivers": "Songs"
}